-- Esquema base: retos (exercise) y sesiones de estudio (study_session).

CREATE TABLE exercise (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_number   INTEGER      NOT NULL UNIQUE,
    title        VARCHAR(200) NOT NULL,
    description  TEXT,
    phase        INTEGER      NOT NULL,
    done         BOOLEAN      NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE study_session (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Una sesion puede estar ligada a un reto, o no (estudio libre).
    -- Si se borra el reto, la sesion queda sin reto (no se borra).
    exercise_id BIGINT REFERENCES exercise(id) ON DELETE SET NULL,
    minutes     INTEGER   NOT NULL,
    difficulty  INTEGER   NOT NULL,
    notes       TEXT,
    studied_at  TIMESTAMP NOT NULL DEFAULT now(),
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_session_exercise ON study_session(exercise_id);
CREATE INDEX idx_session_studied_at ON study_session(studied_at);
