-- Milestone 1: catalogo de conceptos y relaciones N:M con retos y sesiones.

CREATE TABLE concept (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL UNIQUE,
    description TEXT,
    category    VARCHAR(80),
    created_at  TIMESTAMP    NOT NULL DEFAULT now()
);

-- Tabla puente reto <-> concepto. La clave primaria compuesta evita duplicados.
CREATE TABLE exercise_concept (
    exercise_id BIGINT NOT NULL REFERENCES exercise(id) ON DELETE CASCADE,
    concept_id  BIGINT NOT NULL REFERENCES concept(id)  ON DELETE CASCADE,
    PRIMARY KEY (exercise_id, concept_id)
);

-- Tabla puente sesion <-> concepto.
CREATE TABLE session_concept (
    session_id BIGINT NOT NULL REFERENCES study_session(id) ON DELETE CASCADE,
    concept_id BIGINT NOT NULL REFERENCES concept(id)       ON DELETE CASCADE,
    PRIMARY KEY (session_id, concept_id)
);

CREATE INDEX idx_exercise_concept_concept ON exercise_concept(concept_id);
CREATE INDEX idx_session_concept_concept  ON session_concept(concept_id);

-- Carga inicial de conceptos comunes para empezar a etiquetar.
INSERT INTO concept (name, description, category) VALUES
('Variables',          'Almacenamiento de datos con nombre.',                     'Fundamentos'),
('Condicionales',      'Toma de decisiones con if/else/switch.',                  'Fundamentos'),
('Bucles',             'Repeticion con for/while.',                               'Fundamentos'),
('Recursion',          'Funciones que se llaman a si mismas.',                    'Algoritmos'),
('HashMap',            'Estructura clave-valor de acceso rapido.',                'Estructuras de datos'),
('Listas',             'Colecciones ordenadas y dinamicas.',                      'Estructuras de datos'),
('Streams',            'Procesamiento declarativo de colecciones en Java.',       'Programacion funcional'),
('Lambdas',            'Funciones anonimas concisas.',                            'Programacion funcional'),
('POO',                'Programacion orientada a objetos.',                       'Paradigmas'),
('Big-O',              'Analisis de complejidad algoritmica.',                    'Algoritmos');
