-- Milestone 2: repaso espaciado (SM-2). Una ficha de repaso por concepto.

CREATE TABLE concept_review (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- UNIQUE: como mucho una ficha de repaso por concepto (relacion 1:1).
    concept_id       BIGINT  NOT NULL UNIQUE REFERENCES concept(id) ON DELETE CASCADE,
    -- Factor de facilidad (EF). Arranca en 2.5; nunca baja de 1.3.
    easiness         DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    -- Cuantas veces seguidas se aprobo (se reinicia a 0 si fallas).
    repetitions      INTEGER NOT NULL DEFAULT 0,
    -- Dias hasta el proximo repaso calculados en la ultima revision.
    interval_days    INTEGER NOT NULL DEFAULT 0,
    -- Fecha en que toca repasar.
    due_date         DATE    NOT NULL,
    last_reviewed_at TIMESTAMP,
    total_reviews    INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_concept_review_due ON concept_review(due_date);
