-- Milestone 5: logros desbloqueados.
-- Las REGLAS de cada logro viven en codigo (enum AchievementCode).
-- Aqui solo guardamos cuales se han desbloqueado y cuando.

CREATE TABLE unlocked_achievement (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL UNIQUE,
    unlocked_at TIMESTAMP   NOT NULL DEFAULT now()
);
