-- V7: banco de errores. Registra bugs/errores encontrados y, cuando se resuelve,
-- su solucion. Permite buscar por texto y filtrar por reto o por estado (resuelto/abierto).

CREATE TABLE error_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description TEXT         NOT NULL,
    -- NULL = todavia sin resolver. Cuando se registra la solucion se rellena
    -- junto con resolved_at; el estado "resuelto" se deriva de resolved_at.
    solution    TEXT,
    -- Un error puede estar ligado a un reto, o no (error general). Si se borra
    -- el reto, el error queda sin reto pero no se pierde (como study_session).
    exercise_id BIGINT REFERENCES exercise(id) ON DELETE SET NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    resolved_at TIMESTAMP
);

CREATE INDEX idx_error_log_exercise ON error_log(exercise_id);
CREATE INDEX idx_error_log_resolved_at ON error_log(resolved_at);
